myproject/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.register, name="register"),
    path('unregister/', views.unregister, name="unregister"),
    path('modify/', views.modify, name="modify"),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
import shop.views
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', shop.views.home, name='home'),
    path('shop/', include('shop.urls')),
    path('accounts/', include('accounts.urls')), # 계정 관리
    path('accounts/', include('allauth.urls')), # 소셜 로그인
]

myproject/shop/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views


urlpatterns = [
    path('', views.home, name="home"),
    path('<int:product_id>/detail/', views.detail, name="detail"),
    path('cart/', views.cart, name="cart"),
    path('<int:product_id>/add_cart/', views.add_cart, name="add_cart"),

    path('count_down/', views.count_down, name="count_down"),
    path('count_up/', views.count_up, name="count_up"),
]

myproject/myproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NAV BAR</title>
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@300&display=swap" rel="stylesheet">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <!-- Link Swiper's CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.css">
    <!-- Swiper JS -->
    <script src="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.js"></script>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <script src="https://use.fontawesome.com/releases/v5.2.0/js/all.js"></script>
    <script src="https://kit.fontawesome.com/c1c46eaf3c.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    <div class="bar"></div>
    <nav class="navbar">
        <ul class="navbar__left">
            <!-- <i class="fa-solid fa-bars"></i>
            <i class="fa-solid fa-magnifying-glass"></i>
            <i class="fa-solid fa-user"></i>
            <i class="fa-solid fa-bag-shopping"></i> -->
            <li><a href="#" class="menu">Menu</a></li>
            <li><a href="#" class="search">Search</a></li>
        </ul>

        <div class="navbar__logo">
            <a href="/" class="logo">CHEG</a>
        </div>

        <ul class="navbar__right">
            {% if user.is_authenticated %}
            <a href="{% url 'accounts:logout' %}" style="padding: 8px 13px;">{{ user.username }}님, 환영합니다!</a>

            
            {% else %}
            <li><a href="#" class="account">Account</a>
                <ul class="sub__account">
                    <li><a href="{% url 'accounts:login' %}">로그인</a></li>
                    <li><a href="{% url 'accounts:register' %}">회원가입</a></li>
                </ul>
            </li>
            <!-- <a href="{% url 'accounts:login' %}">로그인</a>
            <a href="{% url 'accounts:register' %}">회원가입</a> -->
            {% endif %}


            <li><a href="{% url 'cart' %}" class="cart">Cart</a></li>

            
        </ul>

        <!-- <a href="#" class="navbar__toggleBtn">
            <i class="fas fa-bars"></i>
        </a> -->
    </nav>
    {% block content %}
    {% endblock %}
</body>
</html>