myproject/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.register, name="register"),
    path('unregister/', views.unregister, name="unregister"),
    path('modify/', views.modify, name="modify"),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
import shop.views
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', shop.views.home, name='home'),
    path('shop/', include('shop.urls')),
    path('accounts/', include('accounts.urls')), # 계정 관리
    path('accounts/', include('allauth.urls')), # 소셜 로그인
]

myproject/shop/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views


urlpatterns = [
    path('', views.home, name="home"),
    path('<int:product_id>/detail/', views.detail, name="detail"),
    path('cart/', views.cart, name="cart"),
    path('<int:product_id>/add_cart/', views.add_cart, name="add_cart"),

    path('count_down/', views.count_down, name="count_down"),
    path('count_up/', views.count_up, name="count_up"),
]

myproject/accounts/models.py
from django.db import models

# Create your models here.

myproject/account/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from shop.models import Member
# Member: user / name / addreses / pnumber / email
from django.views.decorators.http import require_POST

# 회원가입
def register(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        address = request.POST['address'],
        pnumber = request.POST['pnumber'],
        email = request.POST['email']

        if Member.objects.filter(username = username).exists():
            return render(request, 'register.html', {'error': "이미 존재하는 사용자입니다."})

        if password == request.POST['password_check']:
            user = Member.objects.create_user(
                username, password, address, pnumber, email
            )
            auth.login(request, user)
            return redirect('/')
        else:
            return render(request, 'register.html', {'error':"비밀번호가 일치하지 않습니다."})
    else:
        return render(request, 'register.html')


# 회원 탈퇴
@require_POST
def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
    # 회원 탈퇴 이후 로그인 화면으로 이동하도록 했습니다.
    return redirect('account:login')


# 회원 정보 변경
def modify(request):
    if request.method == "POST":
        pass


# 로그인
def login(request):
    pass


# 로그아웃
def logout(request):
    pass

myproject/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from shop.models import Member
# Member: user / name / addreses / pnumber / email
from django.views.decorators.http import require_POST
from django.contrib.auth.models import User #django에 내장된 유저 객체
import os

# 회원가입
def register(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        name = request.POST['name']
        pnumber = request.POST['pnumber']
        email = request.POST['email']

        if User.objects.filter(username = username).exists():
            return render(request, 'register.html', {'error': "이미 존재하는 사용자입니다."})

        if password == request.POST['password_check']:
            user = User.objects.create_user(
                username=username, password=password
            )
            auth.login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            Member(user=user, name=name, pnumber=pnumber, email=email).save()

            return redirect('/')
        else:
            return render(request, 'register.html', {'error':"비밀번호가 일치하지 않습니다."})
    else:
        return render(request, 'register.html')

        
# 필요하다고 해서 임시로 넣어둠
def unregister(request):
    pass

# 회원 탈퇴
@require_POST
def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
    # 회원 탈퇴 이후 로그인 화면으로 이동하도록 했습니다.
    return redirect('account:login')


# 회원 정보 변경

def modify(request):
    if request.method == 'GET':
        return render(request, 'modify.html')

    elif request.method == 'POST':
        # 장고에 회원가입된 아이디, 비밀번호 변경
        target = request.user

        # Member 객체의 회원정보 변경
        # Member(user=user, name=name, address=address, pnumber=pnumber, email=email) 에서 목표 user을 가지는 Member을 찾는다.
        target_member = Member.objects.filter(user=target)

        username = request.POST['username']
        password = request.POST['password']
        name = request.POST['name']
        address = request.POST['address']
        pnumber = request.POST['pnumber']
        email = request.POST['email']

        target.username = username
        target.password = password
        target.save()

        for object in target_member:
            object.name = name
            object.address = address
            object.pnumber = pnumber
            object.email = email
            object.save()

        return render(request, 'home.html')

# 로그인
def login(request):
    # POST 요청시 로그인 검사
    if request.method == 'POST':
        id_input = request.POST['username']
        pw_input = request.POST['password']
        user = auth.authenticate(request, username=id_input, password=pw_input)
        if user is not None:
            auth.login(request, user)
            return redirect('home')
        else:
            return render(request, 'login.html')
    # GET 요청시 로그인 페이지 실행
    else:
        return render(request, 'login.html')


# 로그아웃
def logout(request):
    auth.logout(request) #auth클래스의 내장메소드인 logout 이용
    return redirect('home')

myproject/accounts/templates/login.html
{% extends 'base.html' %}
{% load socialaccount %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <script src="https://use.fontawesome.com/releases/v5.2.0/js/all.js"></script>
    <script src="https://kit.fontawesome.com/c1c46eaf3c.js" crossorigin="anonymous"></script>

</head>
<!-- 로그인 후 이용가능하다는 메시지 호출 -->
{% for message in messages %}
<script>
    alert("{{ message }}");
</script>
{% endfor %}
<!-- 메시지 호출 끝 -->

<main class="main">
    <div class="container">
        <section class="wrapper">
            <div class="heading">
                <h1 class="text text-large">로그인</h1>
                <p class="text text-normal">신규회원 이신가요? <span><a href="{% url 'accounts:register' %}" class="text text-links">새 계정 만들기</a></span>
                </p>
            </div>
            <form name="login" class="form" action="{% url 'accounts:login' %}" method="POST">
                {% csrf_token %}
                <div class="input-control">
                    <label for="text" class="input-label" hidden>아이디</label>
                    <input type="text" name="username" class="input-field" placeholder="아이디">
                </div>
                <div class="input-control">
                    <label for="password" class="input-label" hidden>비밀번호</label>
                    <input type="password" name="password" class="input-field" placeholder="비밀번호">
                </div>
                <div class="input-control">
                    <input type="submit" style="margin: auto;" name="submit" class="input-submit" value="로그인">
                </div>
            </form>
            <div class="striped">
                <span class="striped-line"></span>
                <!-- <span class="striped-text">또는</span> -->
                <span class="striped-line"></span>
            </div>
            <div class="method">
                <div class="method-control">
                    <a href="{% provider_login_url 'google' %}" class="method-action">
                    <i class="ion ion-logo-google"></i>
                    <span>구글 로그인</span>
                    </a>
                </div>
                <div class="method-control">
                    <a href="{% provider_login_url 'kakao' %}" class="method-action-kakao">
                    <i class="ion ion-logo-kakao"></i>
                    <span></i>카카오 로그인</span>
                    </a>
                </div>
            </div>
        </section>
    </div>
</main>
<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

</html>
{% endblock %}

myproject/accounts/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>로그아웃 html</h2>
</body>
</html>

myproject/accounts/templates/modify.html
<h1>회원정보 수정</h1>
<form action="{% url 'accounts:modify' %}" method="POST">
    {% csrf_token %}
    <br><br>

    {% if error %}
        <p>{{error}}</p>
        <br>
    {% endif %}

    <h3>아이디</h3>
    <input type="text" name="username">
    <br><br>
    <h3>비밀번호</h3>
    <input type="password" name="password">
    <br><br>
    <h3>이름</h3>
    <input type="text" name="name">
    <br><br>
    <h3>휴대전화</h3>
    <input type="tel" name="pnumber">
    <br><br>
    <h3>주소</h3>
    <input type="address" name="address">
    <br><br>       
    <h3>이메일</h3>
    <input type="email" name="email">
    <br><br>
    <input type="submit" value="제출하기">

</form>

myproject/accounts/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- <h1>회원가입</h1>
<form action="{% url 'accounts:register' %}" method="POST">
    {% csrf_token %}
    <br><br>

    {% if error %}
        <p>{{error}}</p>
        <br>
    {% endif %}

    <h3>아이디</h3>
    <input type="text" name="username">
    <br><br>
    <h3>비밀번호</h3>
    <input type="password" name="password">
    <br><br>
    <h3>비밀번호 확인</h3>
    <input type="password" name="password_check">
    <br><br>
    <h3>이름</h3>
    <input type="text" name="name">
    <br><br>
    <h3>휴대전화</h3>
    <input type="tel" name="pnumber">
    <br><br>        
    <h3>이메일</h3>
    <input type="email" name="email">
    <br><br>
    <input type="submit" value="제출하기">

</form> -->

<!DOCTYPE html>
<html lnag="en">
<head>
    <meta charset="UTF-8">
    <title>회원가입</title>
    <link href="{% static 'css/register.css' %}" rel="stylesheet"/>
</head>
  
<body>
  <div class ="main-signup">
        <!--회원가입 부분-->
    <header>
      <h1>회원가입</h1>   
    </header>
    <br>
    <br>
                       
        <section class="signup-wrap">
       
            <div>
                <!--아이디,비번,비번재확인-->
              <h3>아이디</h3>
                 <div style="display: flex;">
                    <span class="signup-input" style="width:100%; margin: 10px 0px 0px 0px">
                        <input id="signup-phone" type="text" placeholder="영문, 숫자 6~12자"></input>
                    </span>
                    <span class="cnum-btn-wrap">
                        <button id="cnum-btn">중복확인</button>
                    </span>
                </div>
             
                 

                <h3>비밀번호</h3>
                <span class="signup-input">
                    <input id="signup-pw" type="text" placeholder="숫자, 영문, 특수문자 조합 최소 8자">></input>
                    <span class="pw-lock"></span>
                </span>

                <span class="signup-input" style="width:100%; margin: 10px 0px 0px 0px">
                    <input id="signup-pww" type="text" placeholder="비밀번호 재확인"></input>
                    <span class="pww-lock"></span>
                </span>

            </div>
            <div style="margin-top: 35px;">
                  <h3>이름</h3>
                   <span class="signup-input">
                    <input id="signup-name" type="text"></input>
                   </span>

            </div>

            <div style="margin-top: 35px;">
                <!--휴대전화-->
                <h3>휴대전화</h3>
                <span class="signup-input">
                    <select id="signup-country" class="selectbox" name="country" onchange="">
                        <option value="ko">대한민국 +82</option>
                    </select>
                </span>
                <div style="display: flex;">
                    <span class="signup-input" style="width:100%; margin: 10px 0px 0px 0px">
                        <input id="signup-phone" type="text" placeholder="전화번호 입력"></input>
                    </span>
                    <span class="cnum-btn-wrap">
                        <button id="cnum-btn">인증번호 받기</button>
                    </span>
                </div>
                
                <span class="signup-input-c" style="margin-top: 10px;">
                    <input id="signup-cnum" type="text" placeholder="인증번호 입력하세요"></input>
                </span>
            </div>

            <div style="margin-top: 35px;">

                <h3>이메일</h3>
                 <span class="signup-input">
                  <input id="signup-email" type="text"></input>
                 </span>

            </div>

            <div>
                <!--가입하기-->
                <div class="signup-btn-wrap" style="margin-top: 40px;">
                    <button id="signup-btn">가입하기</button>
                </div>
            </div>
        </section>
    </div>    
</body>
</html>
{% endblock %}

myproject/accounts/templates/unregister.html
{% extends 'base.html' %}
{% block content %}
    <h1>회원 탈퇴</h1>
    <form method="POST" action="{% url 'unregister' %}">
        
    </form>
{% endblock %}